"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useCallback, useEffect, useState } from "react";
import { apiPost, apiPut, maintenanceApi } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import { DEFAULT_INSPECTION_ITEMS, INSPECTION_ITEM_STATUSES, INSPECTION_OVERALL_STATUSES, INSPECTION_TYPES } from "@/lib/constants";
import { toApiDate, toInputDate, todayInputDate } from "@/lib/format";
import type { Inspection, InspectionItem, InspectionItemStatus, InspectionOverallStatus, InspectionPayload, InspectionType, PageResult } from "@/lib/types";
import { MaintenanceEmptyState, MaintenancePageHeader, MaintenanceStatusBadge, MaintenanceTable, Pagination } from "@/components/maintenance/Maintenance";

type FormState = { license_plate: string; driver_id: string; inspection_type: InspectionType; inspection_date: string; overall_status: "" | InspectionOverallStatus; inspector: string; notes: string; items: InspectionItem[] };
type Filters = { search: string; license_plate: string; driver_id: string; inspection_type: string; overall_status: string; from_date: string; to_date: string; has_failed_items: boolean; has_linked_work_order: string };
const defaultItems = () => DEFAULT_INSPECTION_ITEMS.map((item_name) => ({ item_name, status: "Not Checked" as InspectionItemStatus, comment: "" }));
const newForm = (): FormState => ({ license_plate: "", driver_id: "", inspection_type: "Daily", inspection_date: todayInputDate(), overall_status: "", inspector: "", notes: "", items: defaultItems() });
function toForm(value: Inspection): FormState { return { license_plate: value.license_plate, driver_id: value.driver_id ? String(value.driver_id) : "", inspection_type: value.inspection_type, inspection_date: toInputDate(value.inspection_date), overall_status: value.overall_status, inspector: value.inspector ?? "", notes: value.notes ?? "", items: value.items.map((item) => ({ ...item, comment: item.comment ?? "" })) }; }
function payload(form: FormState): InspectionPayload { return { license_plate: form.license_plate, driver_id: form.driver_id ? Number(form.driver_id) : null, inspection_type: form.inspection_type, inspection_date: toApiDate(form.inspection_date), overall_status: form.overall_status || null, inspector: form.inspector || null, notes: form.notes || null, archived: false, items: form.items.map(({ item_name, status, comment }) => ({ item_name, status, comment: comment || null })) }; }

export default function InspectionsPage() {
  const params = useSearchParams(); const { can } = useAuth(); const canCreate = can("inspectionsCreate"); const canManage = can("inspectionsWrite");
  const [filters, setFilters] = useState<Filters>({ search: params.get("search") ?? "", license_plate: params.get("license_plate") ?? "", driver_id: params.get("driver_id") ?? "", inspection_type: params.get("inspection_type") ?? "", overall_status: params.get("overall_status") ?? "", from_date: params.get("from_date") ?? "", to_date: params.get("to_date") ?? "", has_failed_items: params.get("has_failed_items") === "true", has_linked_work_order: params.get("has_linked_work_order") ?? "" });
  const [result, setResult] = useState<PageResult<Inspection>>({ items: [], page: 1, page_size: 20, total: 0, pages: 0 }); const [form, setForm] = useState<FormState>(newForm); const [editingId, setEditingId] = useState<number | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async (page = 1, values = filters) => { setLoading(true); setError(null); try { setResult(await maintenanceApi.getInspections({ page, page_size: 20, ...values, from_date: toApiDate(values.from_date), to_date: toApiDate(values.to_date), has_failed_items: values.has_failed_items || undefined, has_linked_work_order: values.has_linked_work_order === "" ? undefined : values.has_linked_work_order === "true" })); } catch (err) { setError(err instanceof Error ? err.message : "Could not load Inspections"); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { void load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  function updateItem(index: number, patch: Partial<InspectionItem>) { setForm((current) => ({ ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) })); }
  async function save(event: React.FormEvent) { event.preventDefault(); setError(null); try { const saved = editingId ? await apiPut<Inspection>(`/inspections/${editingId}`, payload(form)) : await apiPost<Inspection>("/inspections", payload(form)); setMessage(`Inspection #${saved.id} ${editingId ? "updated" : "created"}.`); setEditingId(null); setForm(newForm()); await load(result.page); } catch (err) { setError(err instanceof Error ? err.message : "Could not save Inspection"); } }
  async function archive(inspection: Inspection) { if (!confirm(`Archive Inspection #${inspection.id}?`)) return; try { await apiPut(`/inspections/${inspection.id}/archive`, {}); setMessage(`Inspection #${inspection.id} archived.`); await load(result.page); } catch (err) { setError(err instanceof Error ? err.message : "Could not archive Inspection"); } }
  function applyFilters() { const query = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => { if (value !== "" && value !== false) query.set(key, String(value)); }); window.history.replaceState(null, "", `/inspections${query.size ? `?${query}` : ""}`); void load(1, filters); }
  const formFailed = form.items.filter((item) => item.status === "Fail").length;
  return <section>
    <MaintenancePageHeader title="Inspections" description="Vehicle checklists, failed items, review status, and the Work Orders created to resolve inspection issues." />
    {error && <div className="error spaced">{error}</div>}{message && <div className="success spaced">{message}</div>}
    {canCreate && <form className="form card fullWidthForm spaced" onSubmit={save}><h2>{editingId ? `Edit Inspection #${editingId}` : "Create Inspection"}</h2>{formFailed > 0 && <div className="error">{formFailed} checklist item(s) failed. The Inspection cannot be marked Passed.</div>}<div className="formGrid"><div className="formRow"><label>License plate</label><input className="input" required value={form.license_plate} onChange={(e) => setForm({ ...form, license_plate: e.target.value })} /></div><div className="formRow"><label>Driver ID</label><input className="input" type="number" value={form.driver_id} onChange={(e) => setForm({ ...form, driver_id: e.target.value })} /></div><div className="formRow"><label>Inspection type</label><select className="select" value={form.inspection_type} onChange={(e) => setForm({ ...form, inspection_type: e.target.value as InspectionType })}>{INSPECTION_TYPES.map((v) => <option key={v}>{v}</option>)}</select></div><div className="formRow"><label>Inspection date</label><input className="input" type="date" required value={form.inspection_date} onChange={(e) => setForm({ ...form, inspection_date: e.target.value })} /></div><div className="formRow"><label>Overall status</label><select className="select" value={form.overall_status} onChange={(e) => setForm({ ...form, overall_status: e.target.value as "" | InspectionOverallStatus })}><option value="">Auto</option>{INSPECTION_OVERALL_STATUSES.map((v) => <option key={v}>{v}</option>)}</select></div><div className="formRow"><label>Inspector</label><input className="input" value={form.inspector} onChange={(e) => setForm({ ...form, inspector: e.target.value })} placeholder="Defaults to current user" /></div><div className="formRow span2"><label>Notes</label><textarea className="input textarea" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></div></div>
      <div className="header"><h2>Checklist</h2><button className="secondaryButton smallButton" type="button" onClick={() => setForm({ ...form, items: [...form.items, { item_name: "", status: "Not Checked", comment: "" }] })}>Add item</button></div><MaintenanceTable><thead><tr><th>Item</th><th>Status</th><th>Comment</th><th /></tr></thead><tbody>{form.items.map((item, index) => <tr key={`${index}-${item.item_name}`}><td><input className="input" required value={item.item_name} onChange={(e) => updateItem(index, { item_name: e.target.value })} /></td><td><select className="select" value={item.status} onChange={(e) => updateItem(index, { status: e.target.value as InspectionItemStatus })}>{INSPECTION_ITEM_STATUSES.map((v) => <option key={v}>{v}</option>)}</select></td><td><input className="input" value={item.comment ?? ""} onChange={(e) => updateItem(index, { comment: e.target.value })} /></td><td><button className="dangerButton smallButton" type="button" disabled={form.items.length === 1} onClick={() => setForm({ ...form, items: form.items.filter((_, i) => i !== index) })}>Remove</button></td></tr>)}</tbody></MaintenanceTable><div className="actions"><button className="button">{editingId ? "Update Inspection" : "Create Inspection"}</button>{editingId && <button className="secondaryButton" type="button" onClick={() => { setEditingId(null); setForm(newForm()); }}>Cancel</button>}</div></form>}
    <div className="card filtersGrid spaced"><input className="input" placeholder="Search plate, driver, inspector, notes" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value })} /><input className="input" placeholder="License plate" value={filters.license_plate} onChange={(e) => setFilters({ ...filters, license_plate: e.target.value })} /><input className="input" type="number" placeholder="Driver ID" value={filters.driver_id} onChange={(e) => setFilters({ ...filters, driver_id: e.target.value })} /><select className="select" value={filters.inspection_type} onChange={(e) => setFilters({ ...filters, inspection_type: e.target.value })}><option value="">All types</option>{INSPECTION_TYPES.map((v) => <option key={v}>{v}</option>)}</select><select className="select" value={filters.overall_status} onChange={(e) => setFilters({ ...filters, overall_status: e.target.value })}><option value="">All statuses</option>{INSPECTION_OVERALL_STATUSES.map((v) => <option key={v}>{v}</option>)}</select><input className="input" type="date" value={filters.from_date} onChange={(e) => setFilters({ ...filters, from_date: e.target.value })} /><input className="input" type="date" value={filters.to_date} onChange={(e) => setFilters({ ...filters, to_date: e.target.value })} /><select className="select" value={filters.has_linked_work_order} onChange={(e) => setFilters({ ...filters, has_linked_work_order: e.target.value })}><option value="">Any Work Order link</option><option value="true">Has linked Work Order</option><option value="false">No linked Work Order</option></select><label className="actions"><input type="checkbox" checked={filters.has_failed_items} onChange={(e) => setFilters({ ...filters, has_failed_items: e.target.checked })} /> Has failed items</label><button className="button" onClick={applyFilters}>Apply filters</button></div>
    {loading ? <div className="card">Loading Inspections...</div> : !result.items.length ? <MaintenanceEmptyState>No Inspections match the current filters.</MaintenanceEmptyState> : <MaintenanceTable><thead><tr><th>ID / Vehicle</th><th>Driver / Inspector</th><th>Type / Date</th><th>Status</th><th>Failed items</th><th>Created Work Order</th><th>Actions</th></tr></thead><tbody>{result.items.map((inspection) => { const failedItems = inspection.items.filter((item) => item.status === "Fail"); return <tr key={inspection.id} className={inspection.overall_status === "Failed" ? "criticalRow" : undefined}><td><Link className="link" href={`/inspections/${inspection.id}`}>#{inspection.id}</Link><br /><strong>{inspection.vehicle_name}</strong><br /><span className="muted">{inspection.license_plate}</span></td><td>{inspection.driver_name ?? inspection.driver_id ?? "-"}<br /><span className="muted">{inspection.inspector ?? "No inspector"}</span></td><td>{inspection.inspection_type}<br /><span className="muted">{inspection.inspection_date}</span></td><td><MaintenanceStatusBadge status={inspection.overall_status} /></td><td>{failedItems.length ? <><span className="dangerBadge">{failedItems.length} failed</span><ul className="failedItems">{failedItems.map((item) => <li key={item.id ?? item.item_name}>{item.item_name}{item.comment ? `: ${item.comment}` : ""}</li>)}</ul></> : "0"}</td><td>{inspection.linked_work_order ? <><Link className="link" href={`/work-orders/${inspection.linked_work_order.id}`}>Work Order #{inspection.linked_work_order.id} created</Link><br /><MaintenanceStatusBadge status={inspection.linked_work_order.status} /></> : "-"}</td><td><div className="actions"><Link className="secondaryButton smallButton" href={`/inspections/${inspection.id}`}>View</Link>{canManage && <><button className="secondaryButton smallButton" onClick={() => { setEditingId(inspection.id); setForm(toForm(inspection)); window.scrollTo({ top: 0, behavior: "smooth" }); }}>Edit</button>{failedItems.length > 0 && !inspection.linked_work_order && <Link className="button smallButton" href={`/work-orders?inspection_id=${inspection.id}&license_plate=${encodeURIComponent(inspection.license_plate)}&title=${encodeURIComponent(`Inspection ${inspection.id} issue`)}&reported_issue=${encodeURIComponent(`${failedItems.length} failed checklist item(s): ${failedItems.map((item) => item.item_name).join(", ")}`)}`}>Create Work Order</Link>}{inspection.linked_work_order && <Link className="secondaryButton smallButton" href={`/work-orders/${inspection.linked_work_order.id}`}>View Existing Work Order</Link>}<button className="secondaryButton smallButton" onClick={() => void archive(inspection)}>Archive</button></>}</div></td></tr>; })}</tbody></MaintenanceTable>}
    <Pagination page={result.page} pages={result.pages} total={result.total} onPageChange={(page) => void load(page)} />
  </section>;
}
