from fastapi import APIRouter
from app.api.v1.endpoints import accidents, audit_logs, auth, bulk_actions, compliance, dashboard, drivers, files, fuel, imports, inspections, maintenance, notifications, papers, reports, reservations, services, vehicle_assignments, vehicle_catalog, vehicle_registration, vehicles, work_orders

api_router = APIRouter()
api_router.include_router(auth.router, prefix="/auth", tags=["auth"])
api_router.include_router(audit_logs.router, prefix="/audit-logs", tags=["audit logs"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(files.router, prefix="/files", tags=["files"])
api_router.include_router(imports.router, prefix="/imports", tags=["imports"])
api_router.include_router(bulk_actions.router, prefix="/bulk-actions", tags=["bulk actions"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["dashboard"])
api_router.include_router(vehicles.router, prefix="/vehicles", tags=["vehicles"])
api_router.include_router(vehicle_registration.router, prefix="/vehicle-registration", tags=["vehicle registration"])
api_router.include_router(vehicle_catalog.router, prefix="/vehicle-catalog", tags=["vehicle catalog"])
api_router.include_router(drivers.router, prefix="/drivers", tags=["drivers"])
api_router.include_router(vehicle_assignments.router, prefix="/vehicle-assignments", tags=["vehicle assignments"])
api_router.include_router(inspections.router, prefix="/inspections", tags=["inspections"])
api_router.include_router(work_orders.router, prefix="/work-orders", tags=["work-orders"])
api_router.include_router(maintenance.router, prefix="/maintenance", tags=["maintenance"])
api_router.include_router(reports.router, prefix="/reports", tags=["reports"])
api_router.include_router(services.router, prefix="/services", tags=["services"])
api_router.include_router(fuel.router, prefix="/fuel", tags=["fuel"])
api_router.include_router(papers.router, prefix="/papers", tags=["papers"])
api_router.include_router(compliance.router, prefix="/compliance", tags=["document compliance"])
api_router.include_router(accidents.router, prefix="/accidents", tags=["accidents"])
api_router.include_router(reservations.router, prefix="/reservations", tags=["reservations"])
