"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { apiGet, maintenanceApi, vehicleAssignmentsApi } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import type { Inspection, MaintenanceTimelineEvent, PageResult, ServiceReminder, Vehicle, VehicleAssignment, VehicleMaintenanceSummary, VehicleServiceOverview, WorkOrder } from "@/lib/types";
import { MaintenanceEmptyState, MaintenanceKpiCard, MaintenancePriorityBadge, MaintenanceStatusBadge, MaintenanceTable, MaintenanceTimeline, Pagination } from "@/components/maintenance/Maintenance";
import { useLanguage } from "@/components/i18n/LanguageProvider";
import { translateStatus, translateType } from "@/i18n/translate";
import { AssignmentHistoryTable } from "@/components/assignments/AssignmentHistoryTable";

type Tab = "overview" | "assignments" | "work-orders" | "services" | "reminders" | "inspections" | "timeline";
const tabs: Array<[Tab, string]> = [["overview", "vehicles.maintenanceOverview"], ["assignments", "vehicles.assignmentTab"], ["work-orders", "workOrders"], ["services", "serviceHistory"], ["reminders", "serviceReminders"], ["inspections", "inspections"], ["timeline", "vehicles.maintenanceTimeline"]];

export default function VehicleDetailsPage({ params }: { params: { id: string } }) {
  const { t } = useTranslation(["modules", "common", "navigation"]);
  const { formatCurrency, formatDate, formatNumber } = useLanguage();
  const { can } = useAuth();
  const vehicleId = Number(params.id);
  const [vehicle, setVehicle] = useState<Vehicle | null>(null); const [summary, setSummary] = useState<VehicleMaintenanceSummary | null>(null);
  const [orders, setOrders] = useState<WorkOrder[]>([]); const [services, setServices] = useState<VehicleServiceOverview[]>([]); const [reminders, setReminders] = useState<ServiceReminder[]>([]); const [inspections, setInspections] = useState<Inspection[]>([]);
  const [assignments, setAssignments] = useState<VehicleAssignment[]>([]);
  const activeAssignment = assignments.find((assignment) => assignment.status === "Active" || assignment.status === "Overdue");
  const [timeline, setTimeline] = useState<PageResult<MaintenanceTimelineEvent>>({ items: [], page: 1, page_size: 20, total: 0, pages: 0 }); const [tab, setTab] = useState<Tab>("overview"); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const loadTimeline = useCallback(async (page = 1) => { try { setTimeline(await maintenanceApi.getVehicleTimeline(vehicleId, page, 20)); } catch (err) { setError(err instanceof Error ? err.message : t("modules:vehicles.detailsLoadError")); } }, [t, vehicleId]);
  useEffect(() => { let active = true; Promise.all([apiGet<Vehicle>(`/vehicles/${vehicleId}`), maintenanceApi.getVehicleSummary(vehicleId), maintenanceApi.getWorkOrders({ vehicle_id: vehicleId, page_size: 20 }), maintenanceApi.getServices({ vehicle_id: vehicleId, page_size: 20 }), maintenanceApi.getReminders({ vehicle_id: vehicleId, page_size: 20 }), maintenanceApi.getInspections({ vehicle_id: vehicleId, page_size: 20 }), maintenanceApi.getVehicleTimeline(vehicleId, 1, 20), vehicleAssignmentsApi.list({ vehicle_id: vehicleId, page_size: 100 })]).then(([v, s, w, serviceRows, reminderRows, inspectionRows, timelineRows, assignmentRows]) => { if (!active) return; setVehicle(v); setSummary(s); setOrders(w.items); setServices(serviceRows.items); setReminders(reminderRows.items); setInspections(inspectionRows.items); setTimeline(timelineRows); setAssignments(assignmentRows.items); }).catch((err) => { if (active) setError(err instanceof Error ? err.message : t("modules:vehicles.detailsLoadError")); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [t, vehicleId]);
  if (error && !vehicle) return <div className="error">{error}</div>; if (loading || !vehicle || !summary) return <div className="card">{t("modules:vehicles.detailsLoading")}</div>;
  return <section>
    <div className="header"><div><h1>{vehicle.license_plate}</h1><p className="muted">{t("modules:vehicles.registrationCountry")}: {vehicle.registration_country ? t(`common:countries.${vehicle.registration_country}`) : t("modules:vehicles.unresolved")} · {t("common:labels.licencePlate")}: {vehicle.license_plate}</p><p className="muted">{vehicle.brand} {vehicle.model} · {translateStatus(vehicle.status_name)} · {vehicle.odometer_km == null ? "-" : formatNumber(vehicle.odometer_km)} km</p></div><div className="actions"><Link className="secondaryButton" href="/vehicles">{t("modules:vehicles.back")}</Link>{can("vehiclesWrite") && <Link className="secondaryButton" href={`/vehicles/edit/${vehicle.id}`}>{t("modules:vehicles.edit")}</Link>}{can("vehicleAssignmentsWrite") && !activeAssignment && vehicle.status === 0 && <Link className="button" href={`/vehicle-assignments?checkout=1&vehicle_id=${vehicle.id}`}>{t("modules:vehicleAssignments.checkOutVehicle")}</Link>}{can("vehicleAssignmentsWrite") && activeAssignment && <Link className="button" href={`/vehicle-assignments?return_id=${activeAssignment.id}`}>{t("modules:vehicleAssignments.returnVehicle")}</Link>}</div></div>
    {error && <div className="error spaced">{error}</div>}
    <nav className="vehicleTabs" aria-label={t("modules:vehicles.maintenanceOverview")}>{tabs.map(([value, label]) => <button className={tab === value ? "vehicleTab active" : "vehicleTab"} key={value} onClick={() => setTab(value)}>{label.startsWith("vehicles.") ? t(`modules:${label}`) : t(`navigation:${label}`)}</button>)}</nav>
    {tab === "overview" && <><div className="kpiGrid spaced"><MaintenanceKpiCard label={t("modules:maintenance.openWorkOrders")} value={summary.open_work_orders} href={`/work-orders?license_plate=${encodeURIComponent(vehicle.license_plate)}`} /><MaintenanceKpiCard label={t("modules:maintenance.criticalWorkOrders")} value={summary.critical_work_orders} tone="danger" /><MaintenanceKpiCard label={t("modules:vehicles.lastService")} value={summary.last_service?.service_date ? formatDate(summary.last_service.service_date) : "-"} href={summary.last_service ? `/services/${summary.last_service.id}` : undefined} /><MaintenanceKpiCard label={t("modules:vehicles.nextService")} value={summary.next_service?.due_date ? formatDate(summary.next_service.due_date) : (summary.next_service?.due_odometer_km ? `${formatNumber(summary.next_service.due_odometer_km)} km` : "-")} /><MaintenanceKpiCard label={t("modules:vehicles.overdueReminders")} value={summary.overdue_reminders} tone="danger" /><MaintenanceKpiCard label={t("modules:maintenance.failedInspections")} value={summary.failed_inspections} tone="danger" /><MaintenanceKpiCard label={t("modules:vehicles.costThisMonth")} value={formatCurrency(summary.maintenance_cost_this_month)} /><MaintenanceKpiCard label={t("modules:vehicles.costThisYear")} value={formatCurrency(summary.maintenance_cost_this_year)} /><MaintenanceKpiCard label={t("modules:vehicles.lifetimeCost")} value={formatCurrency(summary.lifetime_maintenance_cost)} /></div><div className="card"><h2>{t("modules:vehicles.lifecycle")}</h2><p className="muted">{t("modules:vehicles.lifecycleDescription")}</p></div></>}
    {tab === "assignments" && <AssignmentHistoryTable assignments={assignments} />}
    {tab === "work-orders" && (!orders.length ? <MaintenanceEmptyState>{t("modules:vehicles.noVehicleRecords")}</MaintenanceEmptyState> : <MaintenanceTable><thead><tr><th>ID</th><th>{t("common:labels.description")}</th><th>{t("common:labels.source")}</th><th>{t("common:labels.priority")}</th><th>{t("common:labels.status")}</th><th>{t("common:status.Assigned")}</th><th>{t("common:labels.cost")}</th></tr></thead><tbody>{orders.map((row) => <tr key={row.id}><td><Link className="link" href={`/work-orders/${row.id}`}>#{row.id}</Link></td><td>{row.title}</td><td>{translateType(row.source)}</td><td><MaintenancePriorityBadge priority={row.priority} /></td><td><MaintenanceStatusBadge status={row.status} /></td><td>{row.assigned_to ?? "-"}</td><td>{formatCurrency(row.total_cost)}</td></tr>)}</tbody></MaintenanceTable>)}
    {tab === "services" && (!services.length ? <MaintenanceEmptyState>{t("modules:vehicles.noVehicleRecords")}</MaintenanceEmptyState> : <MaintenanceTable><thead><tr><th>ID</th><th>{t("common:labels.type")}</th><th>{t("common:labels.date")}</th><th>{t("common:labels.odometer")}</th><th>{t("common:labels.workshop")}</th><th>{t("common:labels.source")}</th><th>{t("common:labels.cost")}</th></tr></thead><tbody>{services.map((row) => <tr key={row.id}><td><Link className="link" href={`/services/${row.id}`}>#{row.id}</Link></td><td>{translateType(row.service_type)}</td><td>{formatDate(row.service_date)}</td><td>{row.odometer_km == null ? "-" : formatNumber(row.odometer_km)}</td><td>{row.workshop ?? "-"}</td><td>{translateType(row.source)}</td><td>{formatCurrency(row.total_cost)}</td></tr>)}</tbody></MaintenanceTable>)}
    {tab === "reminders" && (!reminders.length ? <MaintenanceEmptyState>{t("modules:vehicles.noVehicleRecords")}</MaintenanceEmptyState> : <MaintenanceTable><thead><tr><th>{t("navigation:serviceHistory")}</th><th>{t("modules:vehicles.dueDate")}</th><th>{t("modules:vehicles.dueOdometer")}</th><th>{t("modules:vehicles.remaining")}</th><th>{t("common:labels.status")}</th><th>{t("navigation:workOrders")}</th></tr></thead><tbody>{reminders.map((row) => <tr key={row.id}><td><Link className="link" href={`/services/reminders?reminder_id=${row.id}`}>{translateType(row.service_type)}</Link></td><td>{row.next_service_date ? formatDate(row.next_service_date) : "-"}</td><td>{row.next_service_odometer_km == null ? "-" : formatNumber(row.next_service_odometer_km)}</td><td>{row.days_left !== null && row.days_left !== undefined ? `${formatNumber(row.days_left)} d` : row.km_left !== null && row.km_left !== undefined ? `${formatNumber(row.km_left)} km` : "-"}</td><td><MaintenanceStatusBadge status={row.status} /></td><td>{row.linked_work_order ? <Link className="link" href={`/work-orders/${row.linked_work_order.id}`}>#{row.linked_work_order.id}</Link> : "-"}</td></tr>)}</tbody></MaintenanceTable>)}
    {tab === "inspections" && (!inspections.length ? <MaintenanceEmptyState>{t("modules:vehicles.noVehicleRecords")}</MaintenanceEmptyState> : <MaintenanceTable><thead><tr><th>ID</th><th>{t("common:labels.type")}</th><th>{t("common:labels.date")}</th><th>{t("common:labels.driver")}</th><th>{t("common:labels.status")}</th><th>{t("modules:vehicles.failed")}</th><th>{t("navigation:workOrders")}</th></tr></thead><tbody>{inspections.map((row) => <tr key={row.id}><td><Link className="link" href={`/inspections/${row.id}`}>#{row.id}</Link></td><td>{translateType(row.inspection_type)}</td><td>{formatDate(row.inspection_date)}</td><td>{row.driver_name ?? "-"}</td><td><MaintenanceStatusBadge status={row.overall_status} /></td><td>{formatNumber(row.failed_item_count)}</td><td>{row.linked_work_order ? <Link className="link" href={`/work-orders/${row.linked_work_order.id}`}>#{row.linked_work_order.id}</Link> : "-"}</td></tr>)}</tbody></MaintenanceTable>)}
    {tab === "timeline" && <section className="card"><h2>{t("modules:vehicles.maintenanceTimeline")}</h2><MaintenanceTimeline events={timeline.items} /><Pagination page={timeline.page} pages={timeline.pages} total={timeline.total} onPageChange={(page) => void loadTimeline(page)} /></section>}
  </section>;
}
