"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { apiGet, maintenanceApi } from "@/lib/api";
import { useAuth } from "@/lib/auth";
import type { Inspection, MaintenanceTimelineEvent, PageResult, ServiceReminder, Vehicle, VehicleMaintenanceSummary, VehicleServiceOverview, WorkOrder } from "@/lib/types";
import { formatMoney, MaintenanceEmptyState, MaintenanceKpiCard, MaintenancePriorityBadge, MaintenanceStatusBadge, MaintenanceTable, MaintenanceTimeline, Pagination } from "@/components/maintenance/Maintenance";

type Tab = "overview" | "work-orders" | "services" | "reminders" | "inspections" | "timeline";
const tabs: Array<[Tab, string]> = [["overview", "Maintenance Overview"], ["work-orders", "Work Orders"], ["services", "Service History"], ["reminders", "Service Reminders"], ["inspections", "Inspections"], ["timeline", "Maintenance Timeline"]];

export default function VehicleDetailsPage({ params }: { params: { id: string } }) {
  const { can } = useAuth();
  const vehicleId = Number(params.id);
  const [vehicle, setVehicle] = useState<Vehicle | null>(null); const [summary, setSummary] = useState<VehicleMaintenanceSummary | null>(null);
  const [orders, setOrders] = useState<WorkOrder[]>([]); const [services, setServices] = useState<VehicleServiceOverview[]>([]); const [reminders, setReminders] = useState<ServiceReminder[]>([]); const [inspections, setInspections] = useState<Inspection[]>([]);
  const [timeline, setTimeline] = useState<PageResult<MaintenanceTimelineEvent>>({ items: [], page: 1, page_size: 20, total: 0, pages: 0 }); const [tab, setTab] = useState<Tab>("overview"); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const loadTimeline = useCallback(async (page = 1) => { try { setTimeline(await maintenanceApi.getVehicleTimeline(vehicleId, page, 20)); } catch (err) { setError(err instanceof Error ? err.message : "Could not load Maintenance Timeline"); } }, [vehicleId]);
  useEffect(() => { let active = true; Promise.all([apiGet<Vehicle>(`/vehicles/${vehicleId}`), maintenanceApi.getVehicleSummary(vehicleId), maintenanceApi.getWorkOrders({ vehicle_id: vehicleId, page_size: 20 }), maintenanceApi.getServices({ vehicle_id: vehicleId, page_size: 20 }), maintenanceApi.getReminders({ vehicle_id: vehicleId, page_size: 20 }), maintenanceApi.getInspections({ vehicle_id: vehicleId, page_size: 20 }), maintenanceApi.getVehicleTimeline(vehicleId, 1, 20)]).then(([v, s, w, serviceRows, reminderRows, inspectionRows, timelineRows]) => { if (!active) return; setVehicle(v); setSummary(s); setOrders(w.items); setServices(serviceRows.items); setReminders(reminderRows.items); setInspections(inspectionRows.items); setTimeline(timelineRows); }).catch((err) => { if (active) setError(err instanceof Error ? err.message : "Could not load vehicle maintenance data"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [vehicleId]);
  if (error && !vehicle) return <div className="error">{error}</div>; if (loading || !vehicle || !summary) return <div className="card">Loading vehicle Maintenance details...</div>;
  return <section>
    <div className="header"><div><h1>{vehicle.license_plate}</h1><p className="muted">Registration country: {vehicle.registration_country_name ?? "Unresolved"} · Licence plate: {vehicle.license_plate}</p><p className="muted">{vehicle.brand} {vehicle.model} · {vehicle.status_name} · {vehicle.odometer_km?.toLocaleString() ?? "-"} km</p></div><div className="actions"><Link className="secondaryButton" href="/vehicles">Back to Vehicles</Link>{can("vehiclesWrite") && <Link className="secondaryButton" href={`/vehicles/edit/${vehicle.id}`}>Edit Vehicle</Link>}</div></div>
    {error && <div className="error spaced">{error}</div>}
    <nav className="vehicleTabs" aria-label="Vehicle maintenance tabs">{tabs.map(([value, label]) => <button className={tab === value ? "vehicleTab active" : "vehicleTab"} key={value} onClick={() => setTab(value)}>{label}</button>)}</nav>
    {tab === "overview" && <><div className="kpiGrid spaced"><MaintenanceKpiCard label="Open Work Orders" value={summary.open_work_orders} href={`/work-orders?license_plate=${encodeURIComponent(vehicle.license_plate)}`} /><MaintenanceKpiCard label="Critical Work Orders" value={summary.critical_work_orders} tone="danger" /><MaintenanceKpiCard label="Last Service" value={summary.last_service?.service_date ?? "-"} href={summary.last_service ? `/services/${summary.last_service.id}` : undefined} /><MaintenanceKpiCard label="Next Service" value={summary.next_service?.due_date ?? (summary.next_service?.due_odometer_km ? `${summary.next_service.due_odometer_km.toLocaleString()} km` : "-")} /><MaintenanceKpiCard label="Overdue Reminders" value={summary.overdue_reminders} tone="danger" /><MaintenanceKpiCard label="Failed Inspections" value={summary.failed_inspections} tone="danger" /><MaintenanceKpiCard label="Cost This Month" value={formatMoney(summary.maintenance_cost_this_month)} /><MaintenanceKpiCard label="Cost This Year" value={formatMoney(summary.maintenance_cost_this_year)} /><MaintenanceKpiCard label="Lifetime Maintenance Cost" value={formatMoney(summary.lifetime_maintenance_cost)} /></div><div className="card"><h2>Maintenance lifecycle</h2><p className="muted">Inspection issue or Service Reminder → Work Order → completed maintenance → Service History → next Service Reminder.</p></div></>}
    {tab === "work-orders" && (!orders.length ? <MaintenanceEmptyState>No Work Orders have been recorded for this vehicle.</MaintenanceEmptyState> : <MaintenanceTable><thead><tr><th>ID</th><th>Title</th><th>Source</th><th>Priority</th><th>Status</th><th>Assigned</th><th>Cost</th></tr></thead><tbody>{orders.map((row) => <tr key={row.id}><td><Link className="link" href={`/work-orders/${row.id}`}>#{row.id}</Link></td><td>{row.title}</td><td>{row.source}</td><td><MaintenancePriorityBadge priority={row.priority} /></td><td><MaintenanceStatusBadge status={row.status} /></td><td>{row.assigned_to ?? "-"}</td><td>{formatMoney(row.total_cost)}</td></tr>)}</tbody></MaintenanceTable>)}
    {tab === "services" && (!services.length ? <MaintenanceEmptyState>No Service records have been recorded for this vehicle.</MaintenanceEmptyState> : <MaintenanceTable><thead><tr><th>ID</th><th>Type</th><th>Date</th><th>Odometer</th><th>Workshop</th><th>Source</th><th>Cost</th></tr></thead><tbody>{services.map((row) => <tr key={row.id}><td><Link className="link" href={`/services/${row.id}`}>#{row.id}</Link></td><td>{row.service_type}</td><td>{row.service_date}</td><td>{row.odometer_km?.toLocaleString() ?? "-"}</td><td>{row.workshop ?? "-"}</td><td>{row.source}</td><td>{formatMoney(row.total_cost)}</td></tr>)}</tbody></MaintenanceTable>)}
    {tab === "reminders" && (!reminders.length ? <MaintenanceEmptyState>No upcoming Service Reminders for this vehicle.</MaintenanceEmptyState> : <MaintenanceTable><thead><tr><th>Service</th><th>Due date</th><th>Due odometer</th><th>Remaining</th><th>Status</th><th>Work Order</th></tr></thead><tbody>{reminders.map((row) => <tr key={row.id}><td><Link className="link" href={`/services/reminders?reminder_id=${row.id}`}>{row.service_type}</Link></td><td>{row.next_service_date ?? "-"}</td><td>{row.next_service_odometer_km?.toLocaleString() ?? "-"}</td><td>{row.days_left !== null && row.days_left !== undefined ? `${row.days_left} days` : row.km_left !== null && row.km_left !== undefined ? `${row.km_left.toLocaleString()} km` : "-"}</td><td><MaintenanceStatusBadge status={row.status} /></td><td>{row.linked_work_order ? <Link className="link" href={`/work-orders/${row.linked_work_order.id}`}>#{row.linked_work_order.id}</Link> : "-"}</td></tr>)}</tbody></MaintenanceTable>)}
    {tab === "inspections" && (!inspections.length ? <MaintenanceEmptyState>No Inspections have been recorded for this vehicle.</MaintenanceEmptyState> : <MaintenanceTable><thead><tr><th>ID</th><th>Type</th><th>Date</th><th>Driver</th><th>Status</th><th>Failed</th><th>Work Order</th></tr></thead><tbody>{inspections.map((row) => <tr key={row.id}><td><Link className="link" href={`/inspections/${row.id}`}>#{row.id}</Link></td><td>{row.inspection_type}</td><td>{row.inspection_date}</td><td>{row.driver_name ?? "-"}</td><td><MaintenanceStatusBadge status={row.overall_status} /></td><td>{row.failed_item_count}</td><td>{row.linked_work_order ? <Link className="link" href={`/work-orders/${row.linked_work_order.id}`}>#{row.linked_work_order.id}</Link> : "-"}</td></tr>)}</tbody></MaintenanceTable>)}
    {tab === "timeline" && <section className="card"><h2>Maintenance Timeline</h2><MaintenanceTimeline events={timeline.items} /><Pagination page={timeline.page} pages={timeline.pages} total={timeline.total} onPageChange={(page) => void loadTimeline(page)} /></section>}
  </section>;
}
